SignUpEmailConfirmation/Models/ErrorViewModel.cs
namespace SignUpEmailConfirmation.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SignUpEmailConfirmation/ViewModels/User.cs
namespace SignUpEmailConfirmation.ViewModels
{
    public class User
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string PasswordConfirm { get; set; }
        public string Email { get; set; }
    }
}

SignUpEmailConfirmation/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SignUpEmailConfirmation.Models;
using SignUpEmailConfirmation.ViewModels;
using System.Diagnostics;

namespace SignUpEmailConfirmation.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index(User user)
        {
            return View(user);
        }

    }
}

SignUpEmailConfirmation/Controllers/SignUpController.cs
using Microsoft.AspNetCore.Mvc;
using SignUpEmailConfirmation.Abstraction.Services;
using SignUpEmailConfirmation.Helpers;
using SignUpEmailConfirmation.ViewModels;
using System.Text.Json;

namespace SignUpEmailConfirmation.Controllers
{
    public class SignUpController : Controller
    {
        readonly ISignUpService _signUpService;

        public SignUpController(ISignUpService signUpService)
        {
            _signUpService = signUpService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(User user)
        {
            if(ModelState.IsValid) //Model istediğimiz şekilde geliyor mu ona bakıyoruz(Yani validation'ları uyguluyor mu). Bu kontrolü yapmazsak validation'ları uygulamadan RedirectToAction çalışıyor ve hatalara bakmaksızın sayfaya yönleniyor.
             //ModelState => Model üzerinde belirlenen Validation'ları kontol eder ve doğrulama yapar.
            {
                await _signUpService.SendConfirmationEmailAsync(user);
                return RedirectToAction("WaitingConfirmation");
            }
            
            return View();
        }

        public IActionResult WaitingConfirmation()
        {
            return View();
        }

        public IActionResult RegisterUser(string id)
        {
            User user = _signUpService.JsonDeserializeUser(id);
            return RedirectToAction("Index", "Home", user);
        }
    }
}

SignUpEmailConfirmation/Views/Home/Index.cshtml
@model SignUpEmailConfirmation.ViewModels.User

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Merhaba @Model.UserName</h1>
    <p>Kayıt işlemi başarılı bir şekilde gerçekleşmiştir.</p>
    <h2>Bilgiler</h2>
    <p>Email: @Model.Email</p>
    <p>Şifre: @Model.Password</p>
</div>

SignUpEmailConfirmation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SignUpEmailConfirmation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SignUpEmailConfirmation.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/alertifyjs@1.14.0/build/css/alertify.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/alertifyjs@1.14.0/build/alertify.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SignUpEmailConfirmation/Views/SignUp/Index.cshtml
@model SignUpEmailConfirmation.ViewModels.User

@{
    Layout = "_Layout";
}

<form asp-action="Index" asp-controller="SignUp" method="post" id="signUpForm">
    <div class="form-group m-3">
        <label for="userName">Kullanıcı Adı</label>
        @Html.TextBoxFor(x => x.UserName, new { @class = "form-control", @required ="required" })
        @Html.ValidationMessageFor(x => x.UserName, "", new { @class = "text-danger" })
    </div>
    <div class="form-group m-3">
        <label for="userName">Şifre</label>
        @Html.TextBoxFor(x => x.Password, new { type = "password", @class = "form-control", @required = "required" })
        @Html.ValidationMessageFor(x => x.Password, "", new { @class = "text-danger" })
    </div>
    <div class="form-group m-3">
        <label for="userName">Şifre Tekrar</label>
        @Html.TextBoxFor(x => x.PasswordConfirm, new { type = "password", @class = "form-control", @required = "required" })
        @Html.ValidationMessageFor(x => x.PasswordConfirm, "", new { @class = "text-danger" })
    </div>
    <div class="form-group m-3">
        <label for="userName">Email</label>
        @Html.TextBoxFor(x => x.Email, new { type = "email", @class = "form-control", @required = "required" })
        @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
    </div>
    <button type="submit" class="btn btn-primary m-3" id>Kayıt Ol</button>
</form>

SignUpEmailConfirmation/Views/SignUp/WaitingConfirmation.cshtml
@{
    Layout = "_Layout";
}

<div class="text-center m-3">
    <p>Lütfen kayıt işleminizi tamamlamak için mail adresinize gönderilen linke tıklayınız.</p>
</div>